services:
  web_chat_client:
    container_name: web_chat_client
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL={API_URL}
    environment:
      - PORT=${WEB_CHAT_CLIENT_DOCKER_PORT}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - GOOGLE_CLIENT_ID=${GOOGLE_AUTH_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_AUTH_CLIENT_SECRET}
    ports:
      - ${WEB_CHAT_CLIENT_LOCAL_PORT}:${WEB_CHAT_CLIENT_DOCKER_PORT}
